language: node_js
node_js:
  - '8'
script:
  - npm test
  - npm run build
after_script:
  - npm run coveralls

after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
